### ISSUE TITLE
Restrict direct pallet_uniques calls

### ISSUE THREAD

**Issue by ilionic** [rmrk-team/rmrk-substrate#151]
Using `BaseCallFilter` disable direct calls to `pallet_uniques` since it could lead to unexpected bugs in rmrk pallets if calling uniques extrinsics  directly. 

[Example](https://github.com/paritytech/cumulus/blob/2fe7a2edba05155c6a5f0f3527e1001aad7aee2e/polkadot-parachains/statemint/src/lib.rs#L126)

**Comment by HashWarlock** [comment]
Here's an example from what I did for Uniques for Phala World integration. This blocks the defined functions & allows the rest of the functions that we needed. 

https://github.com/Phala-Network/khala-parachain/blob/61acdfb4fc75413522b21bb3b0a9775cfd0fff83/runtime/khala/src/lib.rs#L301-L322

I think the RMRK pallet will only need access to the function `set_accept_ownership` since it will be needed for Collections that get transferred to a new owner which requires the new owner to call the `set_accept_ownership` before facilitating the transfer. Other Calls can be ignored.
