### ISSUE TITLE
Decouple RMRK pallets from pallet uniques

### ISSUE THREAD

**Issue by Yuripetusko** [rmrk-team/rmrk-substrate#166]
At the moment to add RMRK pallets to your parachain you also will be getting pallets unique, and there's no way to have RMRK pallets without unique. 

While this helped develop faster and safer as all the benchmarking for uniques was done and pallets were tried and tested, in the long term this tight coupling can bring unwanted overhead as RMRK pallets will have to be always synced with pallets uniques. Moreover it can be confusing for new developers that RMRK pallets use uniques constants and storage.

The proposal is to decouple RMRK pallets from pallet uniques by forking uniques and renaming and replacing the matching code where appropriate and adding RMRK code in the fork etc.

**Comment by h4x3rotab** [comment]
Forking uniques: good, since we can move fast and make the changes we need without being blocked by the upstream.

If we go with this way, I suggest to gradually commit the change on our side to the upstream. After all RMRK is the most battle-tested NFT protocol in the polkadot ecosystem. There's a high chance our demand can stand as a NFT standard.

Decoupling from uniques: I’m not sure. The best thing uniques can give us is the compatibility. It’s likely a XCM ecosystem will grow up on top of the official pallet. If we use uniques as the base of RMRKCore, we can benefit from all the XCM compatibility and maybe some other ecosystem development for free.

If we really want to build our own decoupled core when maintaining a reasonable connection with the FRAME ecosystem, I’d suggest to propose a abstraction like the Currency trait to isolate the implementation and the interface. This is how ORML can still fit into the FRAME eco.

**Comment by ilionic** [comment]
Closing this for now as we can push RMRK pallets requirements upstream.
