### ISSUE TITLE
Remove Locks when selling or unlisting an NFT

### ISSUE THREAD

**Issue by HashWarlock** [rmrk-team/rmrk-substrate#267]
## Description
Currently `Lock`s are set to `false` instead of being removed whenever they are released in `unlist_nft` and `accept_offer`. We should remove the `Lock` to reduce space.

**Comment by Szegoo** [comment]
@HashWarlock Just to let you know so that you don't work on something that has already been done, a small part of this issue has been fixed [here](https://github.com/rmrk-team/rmrk-substrate/pull/264/files#diff-cb1d25918280add5a3519e7110127e24250be35513611d0c8217e12ae35f671eR1000-R1010).
I assume that the PR for this issue would also make a migration to remove unnecessary storage items.
And I assume that a test could be written for this. So do you want me to revert the lines I have changed inside my PR regarding this issue so that there would be a separate PR for this?

**Comment by HashWarlock** [comment]
> @HashWarlock Just to let you know so that you don't work on something that has already been done, a small part of this issue has been fixed [here](https://github.com/rmrk-team/rmrk-substrate/pull/264/files#diff-cb1d25918280add5a3519e7110127e24250be35513611d0c8217e12ae35f671eR1000-R1010). I assume that the PR for this issue would also make a migration to remove unnecessary storage items. And I assume that a test could be written for this. So do you want me to revert the lines I have changed inside my PR regarding this issue so that there would be a separate PR for this?

It would be a separate PR. Thank you for letting me know.
